### ISSUE TITLE
[Danik] Please see this

### ISSUE THREAD

**Issue by XtremePlayzCODE** [XtremePlayzCODE/XPocket#2]
The folders and files are based off of [ClearSky.](http://github.com/ClearSkyTeam/ClearSky)

xplib and xprotocol are finished.
xpocket will be up to me to modify.

xplib: spl
xprotocol: raklib
xpocket: pocketmine

I may need you to see any new commits from [ClearSky](http://github.com/ClearSkyTeam/ClearSky) and put those commits on to XPocket **WHEN IT IS FINISHED**.

**Comment by daniktheboss** [comment]
Ok sure thing

**Comment by XtremePlayzCODE** [comment]
Thank you very much
