### ISSUE TITLE
baseclassloader.php

### ISSUE THREAD

**Issue by daniktheboss** [XtremePlayzCODE/XPocket#3]
./start.sh

Fatal error: Uncaught Error: Call to undefined function xplib_autoload_register() in /home/pi/Desktop/XPocket/src/xplib/BaseClassLoader.php:99
Stack trace:
#0 /home/pi/Desktop/XPocket/src/xpocket/XPocket.php(96): BaseClassLoader->register(true)
#1 {main}
  thrown in /home/pi/Desktop/XPocket/src/xplib/BaseClassLoader.php on line 99

**Comment by XtremePlayzCODE** [comment]
Must not of renamed every `spl_autoload_register()` to `xplib_autoload_register`. I will see what I can do.

**Comment by daniktheboss** [comment]
K

**Comment by XtremePlayzCODE** [comment]
I need your help finding `spl_autoload_register` cuz i cant

**Comment by daniktheboss** [comment]
where? in one of the php files?

**Comment by daniktheboss** [comment]
I'll see genisys file

**Comment by XtremePlayzCODE** [comment]
in src/xplib/

**Comment by daniktheboss** [comment]
Ok if I use genisys it works... soooo

**Comment by XtremePlayzCODE** [comment]
genisys is not the biggest deal here u know

**Comment by XtremePlayzCODE** [comment]
maybe use spl from genisys and rename spl to xplib in directories etc.

**Comment by daniktheboss** [comment]
Ok I'll look

**Comment by XtremePlayzCODE** [comment]
im streaming now

**Comment by daniktheboss** [comment]
Streaming? Youtube?

**Comment by XtremePlayzCODE** [comment]
ye

**Comment by XtremePlayzCODE** [comment]
did you find it yet?

**Comment by daniktheboss** [comment]
What's ur youtube

**Comment by XtremePlayzCODE** [comment]
[this](youtube.com/c/XtremePlayzGames)

**Comment by XtremePlayzCODE** [comment]
did u find the spl_autoload_register yet

**Comment by XtremePlayzCODE** [comment]
i need to see where it is defined

**Comment by daniktheboss** [comment]
No I'm not home yet... I'll work on it tomorow

**Comment by daniktheboss** [comment]
How long have u been writing php?

**Comment by XtremePlayzCODE** [comment]
Ok then.
I've been practicing PHP for a year now

**Comment by daniktheboss** [comment]
I was looking for it couldn't find it

**Comment by XtremePlayzCODE** [comment]
Do you think it is a PHP thing then?

**Comment by XtremePlayzCODE** [comment]
yeah its a PHP built in thing

**Comment by daniktheboss** [comment]
Yea I think

**Comment by XtremePlayzCODE** [comment]
There we go
